### ISSUE TITLE
Greasemonkey shim script doesn't work.

### ISSUE THREAD

**Issue by CrazyLittle** [cballou/Turntable.FM-Squared#14]
Clicking on the Firefox greasemonkey link doesn't work: https://github.com/cballou/Turntable.FM-Squared/raw/master/greasemonkey/tt-squared.user.js

It does bring up the Greasemonkey pop-up, but it fails to load the script itself.  As per the contents of that file it looks like a lot of the links in the metadata aren't accurate, and point to other scripts such as:

codebase: 'http://userscripts.org/scripts/source/6178.user.js',

which is a flickr.com script.

**Comment by CrazyLittle** [comment]
I re-wrote the shim script as below:

``` javascript
// @resource      myCustomCss https://raw.github.com/cballou/Turntable.FM-Squared/master/greasemonkey/tt-squared.css
// ==/UserScript==

GM_addStyle (GM_getResourceText ("myCustomCss") );
document.body.appendChild(document.createElement("script")).src="https://raw.github.com/cballou/Turntable.FM-Squared/master/tt-squared.js";
```

**Comment by tropicanajones** [comment]
I'm fairly new to programming and github - what should I do with your above notation in order to make this work for me? I cloned the repo, should I add the code you've written above in the tt-squared.user.js file located in the greasemonkey folder? Any help would be appreciated, I'd love to have this extension for TT!

Thank you!
Christina

**Comment by CrazyLittle** [comment]
Here's a fork of the greasemonkey script with my suggested changes: 

https://github.com/CrazyLittle/Turntable.FM-Squared/raw/master/greasemonkey/tt-squared.user.js

**Comment by cballou** [comment]
I'll give that one a shot.
