### ISSUE TITLE
Chat box erasing text

### ISSUE THREAD

**Issue by EmptyJay** [cballou/Turntable.FM-Squared#21]
I love the extension, but I've had to disable it. When I'm typing in the chat box it will randomly erase everything I've typed. It gets pretty annoying trying to type something only to hit enter and see only the last word or two get sent.

Running in Chrome 21.0.1180.89 on Mac OS X 10.8.1

**Comment by cballou** [comment]
Hey EmptyJay, this may have been caused if you had auto-respond enabled in the room. I have updated the code so that it will now save a copy of anything you have typed and restore it after the auto-respond message is sent. Let me know if this fixes the problem. If not, any additional details would be awesome. Generally the emptying of the text had been caused by a new message being generated/sent by the system.

**Comment by EmptyJay** [comment]
It appears to have solved the issue.

I had actually removed all the triggers and responses, but for some reason
not just turned off auto-respond.

Thanks!

Matthew
