### ISSUE TITLE
Chat window wrap issues

### ISSUE THREAD

**Issue by Xenocide122** [cballou/Turntable.FM-Squared#5]
When chatting (even with a widescreen) the chat window gets pushed over to the left and gets stuck there until i click in the empty text box and drag to the left.

**Comment by cballou** [comment]
Thanks Xen. To clarify, is this only occuring after you have typed a long message that extends beyond the text width, or does it begin that way?

I've seen something similar happen if I type a long message that extends beyond the chat message input length (due to excessive padding extending beyond the parent container). If that's the problem, I think it'll be a fairly quick fix.

**Comment by Xenocide122** [comment]
Yea looks like i am having the same issue... only happens when i type a long message that extends beyond the text width.

**Comment by cballou** [comment]
Should be fixed. Switched the box model on the input so it's 100% width minus padding and borders instead of the usual box model.
